### ISSUE TITLE
Permissions not saved

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#74]
Change the permissions for any tour and step. You get a success message that they have been changed but they are never changed.

![perms](https://user-images.githubusercontent.com/1296369/218307487-95bde802-9f2a-49c3-a922-9ed56ae084b2.gif)

**Comment by brianteeman** [comment]
Looking in the database after saving a tour you can see that two records have been created in the database - obviously there should only be one 

![image](https://user-images.githubusercontent.com/1296369/218328110-39dbaa84-07b0-4b25-8c15-b0c00edbd6fd.png)

For a step there is only one row but its still not used
![image](https://user-images.githubusercontent.com/1296369/218328364-e629ed72-7010-4125-b60c-94153c763f1c.png)

**Comment by brianteeman** [comment]
Retested 16Feb
The records in the database are correct now BUT only the changes in tours work

**Comment by obuisard** [comment]
Strange enough, the permission assignments work on new steps, not the core ones.

**Comment by obuisard** [comment]
Ok, the issue was that we are missing the asset column id in the steps table - dugh, I totally missed that one.
However, to keep is simple and since the team does not see any use case where a user would need to change permissions if the tour permissions are set, I am removing the permissions tab on steps. PR to follow.
