### ISSUE TITLE
Featured & Locked

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#83]
Each tour has these three fields in the database but they dont appear to be used anywhere

**Comment by aze088** [comment]
Notes was added in my latest build. As for the others, no idea.

**Comment by brianteeman** [comment]
Confirmed Notes is now used - title updated

**Comment by obuisard** [comment]
The 'locked 'column is used for tours that have language keys instead of plain text in their records. It allows tours in a multilingual environment to remain intact (a save would remove the language keys) and it will allow third party developers to also ship tours users cannot override but just duplicate, delete, archive or unpublish.

**Comment by obuisard** [comment]
The 'featured' column was added for a feature we have no time to put in: featured tours would have priority in the list of tours available for a run.

**Comment by brianteeman** [comment]
Locked: - so the intention is for the tours to be readonly? If so then I would expect the UI to have some sort of indicator to show that. BUT in all my tests with a locked tour I have not been restricted in what I can do so now i am confused

Featured: fair enough but then I would remove the field from the table. It can always be added if the feature is developed in the future

**Comment by obuisard** [comment]
I have removed those columns
